### ISSUE TITLE
Add EVD onset-to-death distribution

### ISSUE THREAD

**Issue by pratikunterwegs** [epiverse-trace/epiparameter#106]
This issue is to request that the EVD onset to death distribution should be restored to {epiparameter}'s database. This distribution was included in previous versions of {epiparameter}, and was useful in the development of {datadelay}.

Re-adding this distribution to {epiparameter} would allow for it to be called in {datadelay} (rather than being defined manually locally as an `epidist`).

**Comment by joshwlambert** [comment]
This will be addressed asap. EVD onset-to-death has already been added to database and now will be put in the package.

**Comment by joshwlambert** [comment]
Updated database, containing Ebola onset-to-death distribution, merged to `main` in #107.
