### ISSUE TITLE
Add how to use a conversion function to build a custom epidist class object

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/epiparameter#114]
_Conversion functions_ are great to convert the usually reported summary statistics to probability distribution parameters.

In a coming vignette about _conversion functions_, they can be shown in an example that solve the problem of how to build a custom `epidist` object with "gamma".

In other words, following this order:
- first, show how to build a custom `epidist` object with "lnorm" probability distribution? (as used in the [showcase](https://github.com/joshwlambert/epiparameterShowcase/blob/becc6723316d8005bec77e9367f1d9e85b3e0351/vignettes/epiparameter_showcase.Rmd#L85-L96))
- then propose a new reasonable problem: "but now, how to build a custom `epidist` object with "gamma"? we can not use mean and sd as probability distribution parameters for gamma."
- this problem should motivate the introduction of _conversion functions_ to solve it.

i.e.: 
 + first, get a new pair of summary statistics from the literature,
 + then, convert these summary statistics to probability distribution parameters, 
 + finally, use `epidist()` to create an `epidist` class object.

``` r
library(epiparameter)
library(tidyverse)

eparams <- epiparam()

# problem: how to build a custom `epidist` object not with "lnorm" but with "gamma"? 

# e.g., let's use this new set of summary statistics borrowed from README
# - disease: Influenza 
# - epi_distribution: incubation_period
# - mean: 2.05
# - sd: 0.49

# show how to use convert functions
gamma_example <- gamma_meansd2shapescale(mean = 2.05,
                                         sd = 0.49)
gamma_example
#> $shape
#> [1] 17.50312
#> 
#> $scale
#> [1] 0.117122

# show how to use the output of convert functions within `epidist()`
epidist(
  disease = "influenza", 
  epi_dist= "incubation_period", 
  prob_distribution = "gamma",
  prob_distribution_params = c(shape = gamma_example$shape, 
                               scale = gamma_example$scale)
)
#> Citation cannot be created as either author, year or DOI is missing
#> Disease: influenza
#> Pathogen: NA
#> Epi Distribution: incubation period
#> Study: No citation available
#> Distribution: gamma
#> Parameters:
#>   shape: 17.503123698459
#>   rate: 8.5381091211995
```

<sup>Created on 2023-03-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Extraction functions can follow a similar path.

**Comment by avallecam** [comment]
Actually, I think we can reuse this idea for training materials. Is it ok for you if we keep it here as a draft idea? and then come back after evaluating if it fits better there or here

**Comment by joshwlambert** [comment]
Yes, sounds good with me. I added the v0.2 tag to this issue as it isn't something I'm going to address for the upcoming release. Let's leave it open and then let me know if you want me to incorporate it into the package or to close the issue.

**Comment by joshwlambert** [comment]
@avallecam are you still planning on using this example in the training material, or perhaps it's already included in the training material? I'm happy to co-author something with you, or do you want to reconsider and have this be documented in {epiparameter}, possibly in a new vignette, as mentioned above?

**Comment by avallecam** [comment]
thanks for raising this up again. I moved this to https://github.com/epiverse-trace/tutorials-middle/issues/97 because it's a more useful reminder for assessments than for fixing sth in the package. For this reason, I'm closing this issue.
