### ISSUE TITLE
Make `print()` method available in other languages

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/epiparameter#116]
#85 introduced a custom `print()` method for `epiparam` and `epidist` objects. These `print()` methods include text, which could be translated for non-English speaking users.

**Comment by joshwlambert** [comment]
@Bisaloo thanks for pointing this out, I'd be happy to add translation functionality. Do you know of any good packages (or even base R functions) that are good for this? I haven't worked on translations in R before.

**Comment by Bisaloo** [comment]
This is the standard package for package translations. By default, `translate_package()` will try to translate everything, including `message()`s, `warning()`s, `stop()`s, which may(?) require too much work for now.

I can have a look and submit a PR in the next weeks to target specifically `print()` methods.

**Comment by joshwlambert** [comment]
@Bisaloo do you still think this is a useful enhancement for the package? 

If so please let me know if you'd like to submit a PR, if not I'm happy to have a go (I haven't used {potools} before but I can take a stab at it), and can tag you in the PR.
