### ISSUE TITLE
Add sections to pkgdown reference index

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/epiparameter#139]
epiparameter exports a large number of functions and it would be very helpful for new users if they were grouped logically (rather than the default, alphabetically) in the pkgdown reference index: https://epiverse-trace.github.io/epiparameter/reference/index.html

- [Example in dplyr](https://dplyr.tidyverse.org/reference/index.html)
- [Example in ggplot2](https://ggplot2.tidyverse.org/reference/index.html)
- [pkgdown documentation to add sections in the index](https://pkgdown.r-lib.org/reference/build_reference.html#reference-index)

**Comment by joshwlambert** [comment]
Thanks for raising Hugo, it was on my todo list, but good to record as an issue. Will address in the same PR as #140.
