### ISSUE TITLE
Remove tidyverse pipe (%>%)

### ISSUE THREAD

**Issue by joshwlambert** [epiverse-trace/epiparameter#15]
It was mentioned in epiverse-trace/blueprints#7 that we should not use the tidyverse pipe. Currently at least one function in {epiparameter} uses the pipe. My suggestion would be to replace these with the base R pipe (`|>`) which would leave the code largely unchanged. If anyone feels differently or would prefer the code to be written without any pipes please let me know.

**Comment by adamkucharski** [comment]
Agree, that change seems sensible.

**Comment by sbfnk** [comment]
Only downside of that approach would be losing backwards compatibility to R <4.1 but this is obviously going to be less and less of a problem. The dependency on R>=4.1 will need to be noted in the DESCRIPTION file.

**Comment by joshwlambert** [comment]
I personally don't mind having the dependency for >=4.1. If we think for whatever reason a large proportion of the user base will not have access to the latest version we should consider an alternative.
