### ISSUE TITLE
Document user-facing changes in NEWS.md

### ISSUE THREAD

**Issue by jamesmbaazam** [epiverse-trace/epiparameter#152]
Today, I noticed that a previous function `lnorm_meansd2musigma` has been renamed to `lnorm_meansd2meanlogsdlog`. It took me a second to find the new function. :)

If it's not too much trouble, could you please document these changes in the NEWS.md file?

**Comment by joshwlambert** [comment]
@jamesmbaazam thanks for raising this point. A NEWS.md file will be added to the package upon the first release (v0.1.0). For now I think recording the changes prior to release - given how volatile the code base is - would create too much work.
