### ISSUE TITLE
Remove/reduce mentioning object classes in README

### ISSUE THREAD

**Issue by joshwlambert** [epiverse-trace/epiparameter#176]
Reading this from a user perspective I think that mentioning these different object classes could be confusing and not really important or significant for an external user. It would be necessary to either remove the text about the classes altogether or, if it's kept, add an explanation of what these classes are and why they are converted, which I don't know if this fits within a quick start section.

I was speaking with @jamesmbaazam about design vignettes and I think that this information about the object classes would be more fitting for this type of vignette rather than the Readme

_Originally posted by @CarmenTamayo in https://github.com/epiverse-trace/epiparameter/pull/151#discussion_r1235081776_

**Comment by joshwlambert** [comment]
There is now minimal reference to objects and classes in the README. Given how the `<epiparameter>` class is the core unit of the package I don't think it should be entirely removed from the README. @jamesmbaazam and @CarmenTamayo please let me know if you agree with how the current README is worded and formatted.

**Comment by jamesmbaazam** [comment]
Thanks for the changes, Josh. It looks good to me.

**Comment by joshwlambert** [comment]
Thanks @jamesmbaazam, I'll close this issue as there aren't any immediate changes required.
