### ISSUE TITLE
add `epidist_db()` argument update to Changelog

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/epiparameter#191]
**Is your feature request related to a problem? Please describe.**
While rerunning code with `epidist_db()` I found that now it extracts more than one parameter with the same arguments. My solution was to replace it with the `epiparam()` + `dplyr::filter()` + `as_epidist()` combo as in [this commit diff](https://github.com/epiverse-trace/howto/commit/804a6e4a4e750604f37fe0eccd96a4ffa131573b).

**Describe the solution you'd like**
If I would like to give it time, I should've looked at the Issues/PR tabs to look at any updates #160 before replacing `epidist_db()`. Now I can recover it with that argument explicitly. However, should we add this update to the Changelog page? I have the impression that the Changelog/News page has little visibility, but it can briefly summarise and register the final modification.

**Comment by joshwlambert** [comment]
Thanks for pointing this out. The NEWS file has not been updated recently and now has some outdated information. 

I think you're issue highlights a larger issue that the NEWS file is most useful when it shows the development of code overtime with version snapshots. I think pushing for {epiparameter} to have more regular, and smaller releases would be beneficial for users interested in how the code is changing, especially for those not used to conducting [git archeology](https://bmuskalla.github.io/blog/2021-01-12-git-archeology/).

**Comment by joshwlambert** [comment]
Another benefit of regular small-scale releases, which relates to your original request, is that it allows a more fine-grained explanation of changes, such as the change in argument of `epidist_db()`. Whereas, as it is now, it does seem appropriate to document the change for the v0.1.0 release given that there was no "official/released" version of `epidist_db()` from which we are changing.
