### ISSUE TITLE
Definitions of scope

### ISSUE THREAD

**Issue by sbfnk** [epiverse-trace/epiparameter#2]
I think it would be worth defining the scope of what types of parameters we are aiming to include - only distribution of delays, or also e.g. reproduction numbers etc.?

Relatedly, we probably want to flag (or limit) if we only include data and summary statistics (e.g. mean of an observed distribution of delays etc) or also modelled estimates.

**Comment by thibautjombart** [comment]
I agree this is key. Maybe as a start we can create issues for all the features that may belong in this package, to form an initial backlog. It may be that seeing the backlog we refine the scope of the package and want to split into separate components, or we may be happy with a single do-it-all package. I am adding a [scope](https://github.com/epiverse-trace/epiparameter/issues?q=is%3Aopen+is%3Aissue+label%3Ascope) label so we can easily find them.

**Comment by joshwlambert** [comment]
@adamkucharski @sbfnk this issue has been open for a while and has become a bit stale. I think it would be good to conclude the discussion on scope and close this issue. 

With regards to my last comment on this issue, all points (for both version 1 and version 2) have been included in the package (with the only exception being the vignette is currently being rewritten).

**Comment by adamkucharski** [comment]
Agree, I think we now have clear picture of where the package fits in, communicated in vignettes etc.
