### ISSUE TITLE
Discretisation method

### ISSUE THREAD

**Issue by sbfnk** [epiverse-trace/epiparameter#230]
I could not find any documentation on how the discretisation is done and e.g. what censoring window is used (should this be an argument?). In the example given the mass at 0 is 0 which is not what I would expect if this represented e.g. a delay distribution.

``` r
library("epiparameter")

param <- epiparameter:::create_prob_dist(
  prob_dist = "gamma",
  prob_dist_params = c(shape = 1, scale = 1),
  discretise = TRUE,
  truncation = NA
)

param$d(0)
#> [1] 0
```

<sup>Created on 2023-12-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by joshwlambert** [comment]
@sbfnk thanks for raising. The discretisation uses [{distcrete}](https://www.repidemicsconsortium.org/distcrete/index.html), with the default interval of discretisation 1 and the endpoint weighting (`w`) also 1. 

Here is a reprex to show why the density for the example you gave is zero at zero, and how it differs if the endpoint weighting is changed. 

``` r
# using the discretisation branch
library("epiparameter")
param1 <- create_epidist_prob_dist(
  prob_dist = "gamma",
  prob_dist_params = c(shape = 1, scale = 1),
  discretise = TRUE,
  truncation = NA, 
  w = 1
)
param1$d(0)
#> [1] 0

param2 <- create_epidist_prob_dist(
  prob_dist = "gamma",
  prob_dist_params = c(shape = 1, scale = 1),
  discretise = TRUE,
  truncation = NA, 
  w = 0.5
)
param2$d(0)
#> [1] 0.3934693

param3 <- create_epidist_prob_dist(
  prob_dist = "gamma",
  prob_dist_params = c(shape = 1, scale = 1),
  discretise = TRUE,
  truncation = NA, 
  w = 0
)
param3$d(0)
#> [1] 0.6321206


plot(param1$d(0:10))
points(param2$d(0:10), col = "red")
points(param3$d(0:10), col = "blue")
```

![](https://i.imgur.com/0HiQjbj.png)

<sup>Created on 2024-05-28 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

I've been working on improving the way the user can specify the discretisation details and the documentation to make it clear what is happening in the `discretisation` branch. I'm happy to make this a draft PR if you think it would be useful to see the changes that have been made.

I'd be happy to discuss changing the discretisation defaults that we use in {epiparameter}, specifically `w`. There was a reason we use 1 but I cannot remember what is this anymore.

_Note_, some of these changes may be removed if we change the distribution interface and backend in the future, however, I think this would be good to improve in the interim for current users.

**Comment by sbfnk** [comment]
> I'd be happy to discuss changing the discretisation defaults that we use in {epiparameter}, specifically `w`. There was a reason we use 1 but I cannot remember what is this anymore.

How exactly the discretisation is best done depends on the use case at hand but for double-censored intervals (e.g. delays that are estimated from a continuous distribution with start and end time only given at the scale of days) it makes more sense to use a 2-day censoring interval than a single day, i.e. Eq. 36 in https://www.medrxiv.org/content/10.1101/2024.01.12.24301247v1.full. You'll see that otherwise e.g. the mean is off:

``` r
dist <- EpiNow2::discretise(EpiNow2::Gamma(1, 1, max = 100))
points(dist[[1]]$pmf, col = "green")
```

![](https://i.imgur.com/jjvKJpX.png)

``` r

mean.distcrete <- function(x, max) {
  sum(x$d(0:max) * 0:max)
}

mean(param1, max = 10)
#> [1] 1.581451
```

``` r
mean(param2, max = 10)
#> [1] 0.9591984
```

``` r
mean(param3, max = 10)
#> [1] 0.5817833
```

``` r

mean(dist)
#> [1] 1.081977
```

<sup>Created on 2024-05-29 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Of course the right method depends mostly on how exactly the discretisation was done in the first place when doing the estimate, but it might be good to choose a good approximation as a default.

**Comment by joshwlambert** [comment]
I'm not sure whether the `interval` argument in `distcrete::distcrete()` can be set to 2 to have the same properties of the 2-day censoring interval you mentioned. Here is a reprex showing the different between `interval = 1` and `interval = 2` (modified from the {distcrete} Get started vignette).

``` r
d0 <- distcrete::distcrete("gamma", interval = 1, shape = 3)
d1 <- distcrete::distcrete("gamma", interval = 2, shape = 3)

x <- 0:10
y0 <- d0$d(x)
y1 <- d1$d(x)


col <- c("gold", "steelblue3")
r <- barplot(rbind(y0, y1), names.arg = 0:10, beside = TRUE,
             xlab = "x", ylab = "Probability mass", las = 1,
             col = col)
legend("topright", c("interval = 1", "interval = 2"), bty = "n", fill = col)
```

![](https://i.imgur.com/EJy8bE5.png)

<sup>Created on 2024-05-29 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

I think the two things we should agree on for the short-term to merge #324 is what the default value for `interval` and `w` should be in `create_epidist_prob_dist()` (currently 1 and 1). Then we can get back into this discussion around distribution interfaces and how it compares to {EpiNow2}.

**Comment by sbfnk** [comment]
If `distcrete` doesn't support suitable censoring I guess the question is whether to consider an alternative, or to address the issue there? In the plot there doesn't seem to be enough probability mass in the first bin with either choice. Are the interval windows not centred correctly perhaps?

**Comment by joshwlambert** [comment]
A short explanation of the binning is here https://www.repidemicsconsortium.org/distcrete/articles/distcrete.html#how-it-works. The second plot shows how `w` influences the mass in each bin. 

The default value of `w` in `distcrete::distcrete()` is 0.5, I think I'll use the {distcrete} defaults in {epiparameter} for now. 

There are a few improvements in PR #324 that will benefit the package even if we haven't yet found the best solution for discretised distributions. I'll set that PR live and merge in the next few days. 

We can continue this discussion and integrate it into the discussion on a new distribution interface.

**Comment by joshwlambert** [comment]
I've found one potential issue with `w = 0.5`, negative quantiles don't make sense for strictly positive distributions, e.g. Gamma.

``` r
w05 <- distcrete::distcrete(name = "gamma", interval = 1, shape = 1, scale = 1, w = 0.5)
w05$q(p = 0)
#> [1] -1
w1 <- distcrete::distcrete(name = "gamma", interval = 1, shape = 1, scale = 1, w = 1)
w1$q(p = 0)
#> [1] 0
```

<sup>Created on 2024-06-04 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Another possible issue when `w = 1` here: https://github.com/reconhub/distcrete/issues/20.

**Comment by joshwlambert** [comment]
@sbfnk this issue has been a bit stale, without a clear path to resolving it. The issues discussed seem, to me, to be coupled to the use of {distcrete}. For now I do not see a way to resolve this. 

I propose we close this issue, and this topic can be discussed and likely resolved if we transplant in new infrastructure for handling distributions (_sensu_ https://github.com/orgs/epiverse-trace/discussions/140)

**Comment by joshwlambert** [comment]
Moving to Done in the v0.2.0 project as I don't plan to make any changes with respect this discussion before the next release. I'll leave the issue open for a couple more weeks to determine if we can find an optimal long-term solution.
