### ISSUE TITLE
Remove piping operators

### ISSUE THREAD

**Issue by thibautjombart** [epiverse-trace/epiparameter#26]
The code currently uses some piping operators %>%. I would recommend not using them in packages as they can make debugging quite hellish.

**Comment by joshwlambert** [comment]
There was some ambiguity before as to whether the opposition was specifically to `%>%`, and not `|>`, or whether the opposition was to using any pipes throughout the package. What are peoples preferences?

**Comment by thibautjombart** [comment]
Good point, I have never used the base pipe to be perfectly honest. Not sure how debugging goes with it.

**Comment by Bisaloo** [comment]
The native pipe should not be used here as it will introduce a dependency on more recent R versions, which our users might not have access to just yet.

**Comment by joshwlambert** [comment]
All pipes have now been removed from the package (as well as any dependency on an R version).
