### ISSUE TITLE
Contributing to the database

### ISSUE THREAD

**Issue by sbfnk** [epiverse-trace/epiparameter#279]
The README sends contributors to a google sheet but that has only two entries - does this need to be update?

**Comment by joshwlambert** [comment]
The google sheet is used as a template for people to add entries. The two entries there are from the package developers to show someone new to the package what each field can include. It is not the same as the library of epidemiological parameters stored and distributed with the package.

I occasionally check this google sheet to integrate any user contributed parameters into the package library.

**Comment by joshwlambert** [comment]
Please suggest alternative methods for users to contribute parameters if you have any ideas. The other option is for a user to fork the repo, add their epidemiological parameters to the JSON database and then make a pull request to the repository. However, the technical threshold for this type of contribution is relatively high. 

In the long-term the WHO Collaboratory database will supersede our library and users can directly contribute to that, but in the short-term I'm happy to improve the method of contribution.

**Comment by sbfnk** [comment]
> The google sheet is used as a template for people to add entries. The two entries there are from the package developers to show someone new to the package what each field can include. It is not the same as the library of epidemiological parameters stored and distributed with the package.
> 
> I occasionally check this google sheet to integrate any user contributed parameters into the package library.

Ah that makes sense - I'll make some suggestion to rephrase / close this issue.
