### ISSUE TITLE
`inst/CITATION` will fail CRAN submission

### ISSUE THREAD

**Issue by sbfnk** [epiverse-trace/epiparameter#297]
An issue that we just came across in EpiNow2: the `inst/CITATION` file refers to `meta$Date` (which would be read from the `DESCRIPTION` file) which, if NULL, is replaced with the system date.

This will be an issue upon CRAN submission if `Date` is not set in `DESCRIPTION`. In that case CRAN automatically gets populated with a POSIX format date so it won't be NULL but the `format` command will produce a warning.

The solution, I think, is to just use the system date.

**Comment by Bisaloo** [comment]
After some testing and back and forth with CRAN, here is what I landed on for linelist if that's helpful: https://github.com/epiverse-trace/linelist/blob/main/inst/CITATION

**Comment by sbfnk** [comment]
We landed on removing the CITATION file altogether as Zenodo updating doesn't seem to be 100% reliable and added maintenance burden.

**Comment by joshwlambert** [comment]
Thanks @sbfnk for raising this, and thanks @Bisaloo for posting a solution. 

I've chosen to use the same approach as epiverse-trace/linelist#125 in PR #314.
