### ISSUE TITLE
Pathogen vs. disease

### ISSUE THREAD

**Issue by sbfnk** [epiverse-trace/epiparameter#3]
What's listed as `pathogen_ID` at the moment is a mixture of pathogens (MERS-CoV, RSV) etc. and diseases (measles, ebola). We might want to make it one or the other, or possibly both as e.g. incubation periods could be different for different diseases caused by the same virus.

**Comment by joshwlambert** [comment]
We have decided to add a `disease` column to the database to enable people to extract distributions from pathogens and diseases.
