### ISSUE TITLE
Data license?

### ISSUE THREAD

**Issue by chartgerink** [epiverse-trace/epiparameter#300]
Currently **epiparameter** provides original data, but that data does not carry a license. MIT license covers the code, but in general it is not recommended to do this for data as it is not intended for that (just like CC licenses are not intended for code).

I don't want to discuss about whether data can be copyrighted to begin with (I can if desired 😊 ); I do think that not having a license can make it more uncertain about how it can be reused freely.

I would recommend to use a separate license for the data, specifically a Public Domain Dedication. This is maximally permissive and also the standard for (meta)data that is aimed to be reused and recompiled. CC BY becomes problematic when compiling databases, as keeping track of the origins of all data points quickly overtakes the size of the actual data (especially problematic in larger databases).

I also mentioned this in the Collaboratory forum for the GREP database: https://collab-forum.who.int/t/epiparameter-hackathon-discussion-thread/186/2?u=chartgerink

**Comment by joshwlambert** [comment]
@chartgerink and I met to discuss the best approach for adding a data license to the {epiparameter} R package. Here I will summarise our discussion and the key points.

- The {epiparameter} R packages requires a data license. This is currently lacking and given the reasons @chartgerink outlines in the original issue description this should be rectified. 
- We should choose an open and permissive license to allow others to freely use and adapt the data that we distribute with the package. The leading contender is [CC0](https://creativecommons.org/publicdomain/zero/1.0/), as this places the database in the public domain.  
- Most epidemiological parameters extracted from published work can be treated as individual data points/facts and thus are free to compile into a database. In other words, the extraction of parameters the literature can happen independent of the license of the publication. However, parameters extracted from pre-compiled sources/databases need to evaluated based on the original license (e.g., provide correct attribution to their sources for CC BY 4.0). We propose to do this on the {epiparameter} pkgdown website for all the sources that require attribution. (We need to check if any of the parameters currently in the database fall into this category).

**Comment by joshwlambert** [comment]
From looking into this topic it seems that R packages can either hold a single license, or multiple licenses.

[The Writing R Extension website states](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Licensing-1):

> Multiple licences can be specified separated by ‘|’ (surrounded by spaces) in which case the user can choose any of the alternatives.

Therefore this setup does work for packages in which one license is applied to the code while another is applied to the data. 

To circumvent this restriction other packages have separated their code from data, and packaged them separately as an R package and a [data package](https://r-pkgs.org/data.html). See https://github.com/ropensci/unconf17/issues/61 for a discussion on package and data licensing.

We will keep the license of the {epiparameter} package as MIT.

For now we want to keep {epiparameter} as a single package with data and code, but also want to address the outstanding issue of data licensing @chartgerink raised in this issue. We are proposing following the convention of [{igraphdata} which circumvent this by specifying several licenses in the `LICENSE` file](https://github.com/igraph/igraphdata/blob/main/LICENSE). 

I will add text to the `LICENSE` file to specify all data in the {epiparameter} package is licensed under [CC0](https://creativecommons.org/public-domain/cc0/).

**Comment by chartgerink** [comment]
Confirming that @joshwlambert and I agreed on this way forward. This note is primarily for reference as I'm out of office for a few weeks and that people don't need to check in with me prior to updating this. 😊
