### ISSUE TITLE
Plot PDF/CDF have misleading x-axis label for offspring distribution

### ISSUE THREAD

**Issue by DxChen0126** [epiverse-trace/epiparameter#309]
At the current version, no matter what kind of distribution was input, plot PDF/CDF only provide plots with x-axis with label "Time since infection", which is not correct for offspring distribution.
--------

Please include a brief description of the problem with a code example:

```r
# insert reprex here
```

---------

**Comment by joshwlambert** [comment]
Thank you for raising this issue @DxChen0126. I have addressed this in PR #315 and the plotting function should now use the name of the epidemiological distribution and the time units as the x-axis label. For example "Serial Interval (Days)". For the offspring distribution, no units are given so the x-axis just states "Offspring Distribution". 

I hope this addresses your issue, if not please feel free to reopen this issue and we can discuss a better solution.
