### ISSUE TITLE
Potential naming conflict

### ISSUE THREAD

**Issue by sbfnk** [epiverse-trace/epiparameter#325]
Just flaggin that the `epidist` class vs. `epidist` package might cause confusion in the future
https://github.com/epinowcast/epidist

**Comment by joshwlambert** [comment]
Thanks for flagging, I had noticed this but didn't feel like it was likely to cause many issues. It does emphasise the notation and clarity of discussing packages, functions, and classes. 

At the moment, my preference is not to change anything. If we decided the class name should change then `<epiparameter>` could be a suitable name as many classes are named after the package that exports them (e.g. `<incidence>`, `<epicontacts>`).

**Comment by joshwlambert** [comment]
Tagging @jamesmbaazam as he mentioned the same thing recently.

**Comment by jamesmbaazam** [comment]
Yes, I was wondering if it would be worth discussing and fixing sooner rather than later. `<epidistribution>` or `<epiparameter>` are good candidates.

**Comment by joshwlambert** [comment]
I don't think anything needs fixing, as it assumes something is broken. There is no technical conflict (e.g. namespace conflict) as the {epidist} package doesn't contain an `epidist()` function (https://epidist.epinowcast.org/reference/index.html). 

Although changing the class names in {epiparameter} could be done quickly we don't want to break scripts using the package. Hence, why I've been hesitant to make this change straight away.

I think the best next steps are to contact the maintainer(s) of {epidist} and discuss what would be best for both packages. What do you both think?

**Comment by joshwlambert** [comment]
The `epidist` class will be renamed `epiparameter` in v0.3.0.
