### ISSUE TITLE
`as_epidist()` not showing up in website function reference

### ISSUE THREAD

**Issue by jamesmbaazam** [epiverse-trace/epiparameter#336]
I was trying to point someone to the `as_epidist()` function but couldn't find the function reference on the website. 

I see that there's a "Coercion" section in the `pkgdown.yml` file (https://github.com/epiverse-trace/epiparameter/blob/325562fb30c7b43176c7fc0c967fa76087b6be13/_pkgdown.yml#L48-L52) but this is not rendered on the website.

**Comment by joshwlambert** [comment]
It's available on the dev site: https://epiverse-trace.github.io/epiparameter/dev/reference/as_epidist.html

This is related to the [current setup of pkgdown in Epiverse](https://github.com/epiverse-trace/blueprints/issues/100). I'll move to option 3 in the options @Bisaloo raised in the blueprints issue.

**Comment by jamesmbaazam** [comment]
Ah, my bad. I didn't realise the function is in the dev version.
