### ISSUE TITLE
Include author list in parameter database

### ISSUE THREAD

**Issue by jamesmbaazam** [epiverse-trace/epiparameter#347]
I was taking a quick glance at the parameter database to see if studies I'd seen elsewhere were included but realised it was quite difficult to do that without having to click on the individual DOIs. I would suggest adding the citation as an column.

This is a simple fix and I can submit a PR if you agree.

**Comment by joshwlambert** [comment]
Thanks for the suggestion, feel free to make a PR with these changes and tag me as the reviewer once you're happy for it to be merged.

Some thoughts on this change: 
- I'm not sure how it will be formatted if the whole citation (`<bibentry>`) is given as a column, you could truncate the citation to the sole author, or first and last author, or first author and et al. 
- You might not need to make a new column, you could add the citation info to the reference column with the DOI

I'll let you decide what is the best implementation.

**Comment by jamesmbaazam** [comment]
Thanks. I went with your suggestions and created a short citation with the first author's family name et al and year, followed by the DOI in the Reference column (See #348).
