### ISSUE TITLE
Potential issues with `distributional`'s native pipe usage

### ISSUE THREAD

**Issue by jamesmbaazam** [epiverse-trace/epiparameter#377]
As epiparameter imports [`{distributional}`](https://github.com/mitchelloharawild/distributional), which has switched to using the native pipe, thereby bumping up the required R version to be > 4.0, I thought to raise this issue so you assess the impact. Happy for you to close if not deemed one to be tracked/fixed.

Relevant issues/discussions:

- https://github.com/mitchelloharawild/distributional/issues/128
- https://github.com/mitchelloharawild/distributional/issues/128

**Comment by joshwlambert** [comment]
Thanks for raising @jamesmbaazam. I wouldn't have spotted this as the oldest version of R we test on in {epiparameter} CI is R-oldrel currently v4.3.3, so I appreciate you raising this before any users had issues. 

Bumping the minimum R version to 4.1.0 would go against the [Epiverse policy of the last 5 releases](https://epiverse-trace.github.io/blueprints/dependencies.html#base-r-support-schedule), which follows the [Tidyverse policy](https://www.tidyverse.org/blog/2019/04/r-version-support/). However, I think there will be a fair number of users with >= 4.1.0 and it would still support the last 4 R versions, so I think it's sensible to make the change.

It's unclear whether {distributional} will remove the use of the `|>`, but I think it's easier if we make this change now, in anticipation of it or other packages increasing their versions. 

As this deviates from Epiverse policy I'll make a note of the reasoning in the design principles vignette.
