### ISSUE TITLE
Allow plotting pdf and cdf on the same base graphics layer 

### ISSUE THREAD

**Issue by jamesmbaazam** [epiverse-trace/epiparameter#409]
I was trying to plot the pdf and cdf of an `<epiparameter>` on the same base graphics layer with `par(mfrow)` but it wasn't working. I realised this is caused by the following line in the plotting method: https://github.com/epiverse-trace/epiparameter/blob/d3ab32849ea65258771a0dbf77519ca8c7d5daca/R/plot.R#L56C3-L56C10. Is there a reason why you're not allowing the griding of these plots? Below is a reprex of the described behaviour

``` r
library(epiparameter)
# Extract influenza serial interval from the database
influenza_serial <- epiparameter_db(
  disease = "influenza",
  epi_name = "serial_interval"
)
#> Returning 1 results that match the criteria (1 are parameterised). 
#> Use subset to filter by entry variables or single_epiparameter to return a single entry. 
#> To retrieve the citation for each use the 'get_citation' function

# Plot the distribution of the serial interval
par(mfrow = c(1, 2))
plot(influenza_serial)
```

![](https://i.imgur.com/SCBZFeL.png)

``` r
plot(influenza_serial, cumulative = TRUE)
```

![](https://i.imgur.com/YfUhtde.png)

<sup>Created on 2024-11-12 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

This is fixed when you remove the code I linked as seen below

``` r
devtools::load_all()
#> ℹ Loading epiparameter
# Extract influenza serial interval from the database
influenza_serial <- epiparameter_db(
  disease = "influenza",
  epi_name = "serial_interval"
)
#> Returning 1 results that match the criteria (1 are parameterised). 
#> Use subset to filter by entry variables or single_epiparameter to return a single entry. 
#> To retrieve the citation for each use the 'get_citation' function

# Plot the distribution of the serial interval
par(mfrow = c(1, 2))
plot(influenza_serial)
plot(influenza_serial, cumulative = TRUE)
```

![](https://i.imgur.com/y8UnKYV.png)

<sup>Created on 2024-11-12 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by joshwlambert** [comment]
Thanks for posting this @jamesmbaazam, I didn't know this was happening. I've resolved the issue in PR #420.
