### ISSUE TITLE
Check whether changes in Marburg parameters are correct

### ISSUE THREAD

**Issue by joshwlambert** [epiverse-trace/epiparameter#45]
Why such a big change in these values?

_Originally posted by @Bisaloo in https://github.com/epiverse-trace/epiparameter/pull/44#discussion_r1004708197_

**Comment by adamkucharski** [comment]
Original reference was extracted from a handful of cases, so Pavlin et al estimates are more recent/detailed. For context, this ref has more on challenges of data for Marburg: https://www.thelancet.com/journals/laninf/article/PIIS1473-3099(22)00647-8/fulltext

**Comment by adamkucharski** [comment]
Have rerun for Pavlin et al and looks like the extraction was actually with lnorm, so the quoted shape/scale match meanlog and sdlog for `extract_param(type = "range", values = c(7,2,13), distribution = "lnorm", samples = 18)`

**Comment by joshwlambert** [comment]
This issue was opened before the new data protocol and the new version of the {epiparameter} database. Marburg has since been added to the new database. Therefore, this issue is no longer relevant. Closing.
