### ISSUE TITLE
Data storage: user facing or internal?

### ISSUE THREAD

**Issue by thibautjombart** [epiverse-trace/epiparameter#5]
The data/ folder is usually used to store .RData files which can be loaded using `data(...)` once the package has been attached. I think the first question is: do we want the user to access the raw data files from R, or are these data more meant to be accessed internally by our functions? My impression is this the latter, but may be wrong. 

If this is the case, I would suggest moving the data to the `inst/` folder, e.g. `inst/extdata/`, which can then be accessed internally using:

`system.file("extdata", "some_file.csv", package = "epiparameter")`

Note that subfolders names have restrictions as R uses some internally.

Relevant read on this topic:

* https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Data-in-packages
* https://stackoverflow.com/questions/13463103/inst-and-extdata-folders-in-r-packaging

**Comment by joshwlambert** [comment]
After discussing this point we are happy to change the data storage to `inst/extdata/` and keep the data internal for now. With regards to issue #4, for now we plan to update the data locally, with the possibility of opening it up to contributions from CMMID coming at a later date.
