### ISSUE TITLE
render-readme.yml cannot handle updating figures

### ISSUE THREAD

**Issue by joshwlambert** [epiverse-trace/epiparameter#65]

**Comment by joshwlambert** [comment]
Updating the figures (and potentially deleting them) will not be done frequently, so we can render the .md locally before pushing.  

Would adding `git add man/figures/` below [`git add README.md`](https://github.com/epiverse-trace/epiparameter/blob/main/.github/workflows/render_readme.yml#L45) not add or delete any figures being changed in the README?

**Comment by Bisaloo** [comment]
It would add new figures and update existing ones but not delete unnecessary ones.

For example, if you remove the instructions to create & display a figure from the README, the old png file would still remain in `man/figures/`.

**Comment by joshwlambert** [comment]
Had a quick look to see if anyone else had solved this issue (e.g. [here](https://github.com/r-lib/actions/blob/v2/examples/render-rmarkdown.yaml)) but couldn't find anything. Are we happy to keep the yml as is and render locally when changing/deleting figures?

**Comment by Bisaloo** [comment]
Please submit a PR to add `man/figures/` alongside `README.md` here and in the packagetemplate repo. It's always better than what we have at the moment but we should keep in mind that we may have to manually clean `man/figures/` sometimes.

Note that both `man/figures/` and `README` can be added in a single `git add` call, no need for 2 separate lines.

**Comment by joshwlambert** [comment]
The issue of adding figures has been tackled here and also in epiverse-trace/packagetemplate@d4c039cfac6a53d1dd255c17f9d95349cd50ea08.

@Bisaloo shall we close this issue for now and revisit possibilities to automate deleting figures in the future?

**Comment by Bisaloo** [comment]
As far as I know, the new workflow should also handle deletions so I think this issue can be closed.
