### ISSUE TITLE
Generate random draw from distribution

### ISSUE THREAD

**Issue by adamkucharski** [epiverse-trace/epiparameter#70]
Currently `epidist` returns the stored probability mass functions, but it could help interoperability with other packages (e.g. simulation based ones) to also have functionality to generate random values based on these distributions (e.g. from `rlnorm()` etc.)

**Comment by Bisaloo** [comment]
The way I've been doing this in the pipeline is by using [distcrete](https://github.com/reconhub/distcrete) which I found works quite well for this.

**Comment by Bisaloo** [comment]
Here are the relevant lines:

https://github.com/epiverse-trace/episoap/blob/a7830b55a793713a3a2c84dfa5df9e4f00de030f/inst/rmarkdown/templates/transmissibility-report/skeleton/skeleton.Rmd#L283-L316

We get the distribution type and parameters from epiparameter, pass it to distcrete, and then can use `x$r()` to generate samples, `x$q()` for quantiles, etc.

**Comment by joshwlambert** [comment]
The new `epidist` class will have methods to return the density and cumulative distributions, and random numbers.

**Comment by joshwlambert** [comment]
@adamkucharski @Bisaloo it would be good to conclude this issue soon. As mentioned above the `<epidist>` class now contains all the functionality described above (with the dependency of {distcrete}). If anything is uncertain about how to use this functionality please let me know. I can provide a reprex if needed.

**Comment by joshwlambert** [comment]
The functionality discussed is fully implemented in {epiparameter} for `<epidist>` (see reprex) and `<vb_epidist>` objects. 

``` r
library(epiparameter)

x <- epidist_db(
  disease = "COVID-19", 
  epi_dist = "incubation period", 
  single_epidist = TRUE
)
#> Using McAloon C, Collins Á, Hunt K, Barber A, Byrne A, Butler F, Casey M,
#> Griffin J, Lane E, McEvoy D, Wall P, Green M, O'Grady L, More S (2020).
#> "Incubation period of COVID-19: a rapid systematic review and
#> meta-analysis of observational research." _BMJ Open_.
#> doi:10.1136/bmjopen-2020-039652
#> <https://doi.org/10.1136/bmjopen-2020-039652>.. 
#> To retrieve the short citation use the 'get_citation' function

density(x, at = 10)
#> [1] 0.03392379
cdf(x, q = 3)
#> [1] 0.1210895
generate(x, times = 10)
#>  [1] 10.899560  2.691221 11.789564  3.060198  3.760280 11.418190  3.984903
#>  [8]  5.321832  5.745600  4.991649
quantile(x, p = 0.4)
#> [1] 4.657102

x <- discretise(x)

density(x, at = 10)
#> [1] 0.04119251
cdf(x, q = 3)
#> [1] 0.1210895
generate(x, times = 10)
#>  [1] 5 6 6 6 4 3 4 7 4 5
quantile(x, p = 0.4)
#> [1] 4
```

<sup>Created on 2023-11-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
