### ISSUE TITLE
Dictionary or fuzzy (approximate) string matching

### ISSUE THREAD

**Issue by joshwlambert** [epiverse-trace/epiparameter#77]
Currently the distribution names in the database do not have a strict form (e.g. can be lnorm, lognormal, log-normal). Therefore, I've changed the matching to use `agrepl()` to matching different inputs. The other method would be to have dictionary functions e.g.

```
lognorms <- function() {
    c("lnorm", "lognormal", "log-normal")
}
if (x %in% lognorms()) ...
```

Is there a preference on one method or to implement a strict naming in the database itself?

**Comment by sbfnk** [comment]
I’d recommend doing the check at the point of data entry and keeping the data base clean and consistent with strict naming. Having to deal with an ever expanding list of possibly ambiguous spellings would risk making things harder to maintain and require more manual intervention / future code.
