### ISSUE TITLE
mean vs meanlog in vignette

### ISSUE THREAD

**Issue by adamkucharski** [epiverse-trace/epiparameter#80]
In the vignette example for EpiEstim, looks like need to convert meanlog and sdlog to mean and sd, e.g.

```
covid_si <- epidist(
  pathogen = "SARS_CoV_2_wildtype",
  delay_dist = "serial_interval"
)

convert_si <- epiparameter::lnorm_musigma2meansd(covid_si$param[["meanlog"]],covid_si$param[["sdlog"]])

rt <- estimate_R(
  incid = data_estim,
  method = "parametric_si",
  config = make_config(list(
    mean_si = convert_si$mean,
    std_si = convert_si$sd
  ))
)
```

**Comment by joshwlambert** [comment]
Thanks for spotting this. I'll take a look into it.

**Comment by joshwlambert** [comment]
This code was removed in https://github.com/epiverse-trace/epiparameter/pull/132. However, keeping this issue open for when writing the transmission vignette.

**Comment by joshwlambert** [comment]
There is no longer a plan to include epidemiological application vignettes in the {epiparameter} package, one of which would have been the transmissibility vignette, therefore this issue can be closed without any further action.
