### ISSUE TITLE
Distribution naming convention

### ISSUE THREAD

**Issue by joshwlambert** [epiverse-trace/epiparameter#86]
There is currently inconsistent naming of distributions in `{epiparameter}`. This affects both users (exported functions) and developers (internal functions). I would like to settle on a single, consistent convention. To me the best three options are:

1) Full distribution names with underscore separate for multiple words (e.g. gamma, lognormal, negative_binomial)
2) Base R (e.g. gamma, lnorm, nbinom)
3) Follow naming style of `{distributional}`. This is the package depended on for most of the distribution objects used in the package. Most of these use full names, but some differ. 

Benefits of option 1 is it is language agnostic and would help if `{epiparameter}` packages were written for other languages (e.g. python or julia) which use different naming conventions. Option 2 is more familiar for R users and is inline with the naming using in `{distcrete}` (which is used in `{epiparameter}` to handle discretised distributions). Option 3 would make the names consistent with the internal handling of the distribution, also the naming convention of the distribution methods follows `{distributional}`.

**Comment by adamkucharski** [comment]
My initial feeling is that (2) would be preferable as it would mean zero (or very little) overhead for regular R users, and some work for other languages, whereas (1) would mean all users have to do some work to change to their language of choice. Unless (3) offers substantial advantages in terms of tests required and reduced potential for errors?

**Comment by joshwlambert** [comment]
I agree option is 2 most consistent for R users. It is also how the `extract_params()` functions are setup now, so wouldn't require any changes on these functions.

**Comment by joshwlambert** [comment]
The database has been updated (in 671169c42f06f9d1aaba6bcae35cc9db38e3e01f) to use the R naming convention for distributions.
