### ISSUE TITLE
Extract parameters from summary statistics (mean, variance)

### ISSUE THREAD

**Issue by adamkucharski** [epiverse-trace/epiparameter#9]
The package includes some initial functionality to extract distribution parameters from median and percentiles via `extract_param()`. However, extraction from values such as mean, variance or COV should be possibly analytically for several distributions.

One existing example is [epitrix::gamma_shapescale2mucv](https://www.repidemicsconsortium.org/epitrix/reference/gamma_tools.html) – if epitrix is not going to be maintained long-term, similar extraction functions could be implemented locally for gamma, lognormal etc.

**Comment by joshwlambert** [comment]
Conversion functions have now been implemented for the lognormal, gamma and weibull distributions, and are on [main](https://github.com/epiverse-trace/epiparameter/blob/main/R/convert_param.R).
